# Generated by Django 4.2 on 2025-03-15 23:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('programs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Defense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='fecha y hora de registro')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='última actualización')),
                ('application_date', models.DateField(verbose_name='Fecha de solicitud')),
                ('scheduled_date', models.DateField(verbose_name='Fecha programada')),
                ('status', models.CharField(choices=[('PENDIENTE', 'PENDIENTE'), ('PROGRAMADA', 'PROGRAMADA'), ('COMPLETADA', 'COMPLETADA'), ('REPROGRAMADA', 'REPROGRAMADA')], default='PENDIENTE', max_length=100, verbose_name='Estado')),
                ('result', models.CharField(choices=[('APROBADO', 'APROBADO'), ('REPROBADO', 'REPROBADO')], max_length=100, verbose_name='Resultado final')),
            ],
            options={
                'verbose_name_plural': 'Sustentaciones',
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='fecha y hora de registro')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='última actualización')),
                ('first_name', models.CharField(max_length=100, verbose_name='Primer nombre')),
                ('second_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Segundo nombre')),
                ('first_surname', models.CharField(max_length=100, verbose_name='Primer apeliido')),
                ('second_surname', models.CharField(blank=True, max_length=100, null=True, verbose_name='Segundo apellido')),
                ('document_number', models.CharField(db_index=True, max_length=11, unique=True, verbose_name='Número de documento')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Correo electrónico')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name_plural': 'Docentes',
            },
        ),
        migrations.CreateModel(
            name='DefenseTeacherThrough',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='fecha y hora de registro')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='última actualización')),
                ('role', models.CharField(choices=[('JURADO', 'JURADO'), ('ASESOR', 'ASESOR')], max_length=100, verbose_name='Rol del docente')),
                ('defense', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evaluations.defense', verbose_name='Sustentación')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evaluations.teacher', verbose_name='Docente')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DefenseStudentThrough',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='fecha y hora de registro')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='última actualización')),
                ('defense', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evaluations.defense', verbose_name='Sustentación')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='programs.student', verbose_name='Estudiante')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='defense',
            name='students',
            field=models.ManyToManyField(through='evaluations.DefenseStudentThrough', to='programs.student'),
        ),
        migrations.AddField(
            model_name='defense',
            name='teachers',
            field=models.ManyToManyField(through='evaluations.DefenseTeacherThrough', to='evaluations.teacher'),
        ),
    ]
