# Generated by Django 4.2 on 2025-03-21 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluations', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='defense',
            options={'ordering': ['created_at'], 'verbose_name_plural': 'Sustentaciones'},
        ),
        migrations.AlterModelOptions(
            name='defensestudentthrough',
            options={'ordering': ['created_at']},
        ),
        migrations.AlterModelOptions(
            name='defenseteacherthrough',
            options={'ordering': ['created_at']},
        ),
        migrations.AlterModelOptions(
            name='teacher',
            options={'ordering': ['created_at'], 'verbose_name_plural': 'Docentes'},
        ),
        migrations.AlterField(
            model_name='defense',
            name='result',
            field=models.CharField(choices=[('APROBADO', 'APROBADO'), ('REPROBADO', 'REPROBADO')], default='N/A', max_length=100, verbose_name='Resultado final'),
        ),
    ]
