# Generated by Django 4.2 on 2025-03-25 15:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('evaluations', '0002_alter_defense_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DefenseComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='fecha y hora de registro')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='última actualización')),
                ('comment', models.TextField(max_length=500, verbose_name='Comentario')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('defense', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evaluations.defense', verbose_name='Sustentación')),
            ],
            options={
                'verbose_name_plural': 'Comentarios de sustentación',
                'ordering': ['created_at'],
            },
        ),
    ]
