# Generated by Django 4.2 on 2025-03-31 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluations', '0003_defensecomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='defensecomment',
            name='new_date',
            field=models.DateField(blank=True, null=True, verbose_name='Nueva fecha'),
        ),
        migrations.AddField(
            model_name='defensecomment',
            name='previous_date',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha anterior'),
        ),
    ]
