# Generated by Django 4.2 on 2025-04-07 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('evaluations', '0004_defensecomment_new_date_defensecomment_previous_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='defensecomment',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'Comentarios de sustentación'},
        ),
    ]
