# Generated by Django 4.2 on 2025-04-24 03:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('evaluations', '0007_teacher_full_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teacher',
            options={'ordering': ['created_at'], 'verbose_name': 'Docente', 'verbose_name_plural': 'Docentes'},
        ),
    ]
