# Generated by Django 4.2 on 2025-05-11 01:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('evaluations', '0008_alter_teacher_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='defense',
            name='period',
            field=models.CharField(default='default', max_length=100, verbose_name='Periodo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='defense',
            name='place',
            field=models.CharField(default='Default', max_length=100, verbose_name='Lugar'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='DocumentDefense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='fecha y hora de registro')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='última actualización')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('file', models.FileField(upload_to='', verbose_name='Archivo')),
                ('defense', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='evaluations.defense', verbose_name='Práctica')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Subido por')),
            ],
            options={
                'verbose_name_plural': 'Documentos de práctica',
                'ordering': ['created_at'],
            },
        ),
    ]
