# Generated by Django 4.2 on 2025-05-11 22:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('evaluations', '0010_alter_defense_result'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='defense',
            options={'ordering': ['created_at'], 'permissions': [('finish_defense', 'Finalizar sustentación')], 'verbose_name_plural': 'Sustentaciones'},
        ),
    ]
