# Generated by Django 4.2 on 2025-05-17 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluations', '0011_alter_defense_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='defense',
            name='academic_session',
            field=models.CharField(choices=[('DIURNA', 'DIURNA'), ('NOCTURNA', 'NOCTURNA')], default='DIURNA', max_length=100),
            preserve_default=False,
        ),
    ]
