services:
  app:
    build: .
    volumes:
      - .:/code
    ports:
      - 8000:8000
    container_name: fup_app
    command: >
      sh -c " python manage.py wait_for_db --settings=fup.settings.development &&
        python manage.py runserver 0.0.0.0:8000 --settings=fup.settings.development"
    environment:
      - MYSQL_DATABASE=fupdb
      - MYSQL_USER=fup
      - MYSQL_PASSWORD=fup_password
      - MYSQL_ROOT_PASSWORD=root_password
  db:
    image: mysql:8.0
    container_name: fup_mysql
    environment:
      - MYSQL_DATABASE=fupdb
      - MYSQL_USER=fup
      - MYSQL_PASSWORD=fup_password
      - MYSQL_ROOT_PASSWORD=root_password
    volumes:
      - ./data/db:/var/lib/mysql
    ports:
      - 3306:3306