sonar.projectKey=fup
sonar.projectVersion=1.0
sonar.projectName=fup
sonar-sources=.
sonar.host.url=http://127.0.0.1:9000
sonar.exclusions=**/tests/**,**/*.css,**/*.js,**/*.html,**/*.scss, **/*.php,**/migrations/**,**/*.mjs,**/*.vue,sonar-project.properties,/fup/**,**/apps.py,**/wsgi.py, **/asgi.py, manage.py,**/manage.py,**/Dockerfile/**, **/Dockerfile, **/docker-compose.yml, **/docker-compose.yml/**
sonar.python.version=3.12
sonar.token=squ_d408f286e9bc459728de7e4876e8644d1ad29e4a
sonar.python.coverage.reportPaths=coverage.xml
sonar.coverage.exclusions=**/tests/**,**/tests.py, **/__init__.py, **/migrations/*, **/urls.py, **/apps.py, **/admin.py, **/wsgi.py, **/asgi.py, manage.py, **/settings.py, **/manage.pyadmi