# Generated by Django 4.2 on 2025-03-15 23:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('evaluations', '0001_initial'),
        ('programs', '0001_initial'),
        ('agreements', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PracticalOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='fecha y hora de registro')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='última actualización')),
                ('title', models.CharField(max_length=100, verbose_name='Titulo')),
                ('description', models.TextField(max_length=2000, verbose_name='Descripción')),
                ('agreement', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='agreements.agreement', verbose_name='Convenio')),
            ],
            options={
                'verbose_name_plural': 'Ofertas prácticas',
            },
        ),
        migrations.CreateModel(
            name='Practice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='fecha y hora de registro')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='última actualización')),
                ('initial_date', models.DateField(verbose_name='Fecha de inicio')),
                ('end_date', models.DateField(verbose_name='Fecha de finalización')),
                ('status', models.CharField(choices=[('PENDIENTE', 'PENDIENTE'), ('EN CURSO', 'EN CURSO'), ('FINALIZADA', 'FINALIZADA')], default='PENDIENTE', max_length=100, verbose_name='Estado')),
                ('practical_offer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='practices.practicaloffer', verbose_name='Oferta práctica')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='programs.student', verbose_name='Estudiante')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='evaluations.teacher', verbose_name='Docente')),
            ],
            options={
                'verbose_name_plural': 'Practicas',
            },
        ),
        migrations.CreateModel(
            name='PracticalOfferStudentThrough',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='fecha y hora de registro')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='última actualización')),
                ('status', models.CharField(max_length=100, verbose_name='Estado')),
                ('practical_offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='practices.practicaloffer', verbose_name='Oferta práctica')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='programs.student', verbose_name='Estudiante')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='practicaloffer',
            name='students',
            field=models.ManyToManyField(blank=True, through='practices.PracticalOfferStudentThrough', to='programs.student'),
        ),
        migrations.CreateModel(
            name='InternshipTracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='fecha y hora de registro')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='última actualización')),
                ('observations', models.TextField(max_length=1000, verbose_name='Observaciones')),
                ('practice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='practices.practice', verbose_name='Práctica')),
            ],
            options={
                'verbose_name_plural': 'Seguimiento de práctica',
            },
        ),
        migrations.CreateModel(
            name='DocumentPractice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='fecha y hora de registro')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='última actualización')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('file', models.FileField(upload_to='', verbose_name='Archivo')),
                ('practice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='practices.practice', verbose_name='Práctica')),
            ],
            options={
                'verbose_name_plural': 'Documentos de práctica',
            },
        ),
    ]
