# Generated by Django 4.2 on 2025-04-07 20:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('practices', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='practice',
            name='practical_offer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='practices.practicaloffer', verbose_name='Oferta práctica'),
        ),
    ]
