# Generated by Django 4.2 on 2025-04-07 22:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('practices', '0002_alter_practice_practical_offer'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='practice',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'Practicas'},
        ),
        migrations.AlterField(
            model_name='practice',
            name='practical_offer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='practices.practicaloffer', verbose_name='Oferta práctica'),
        ),
    ]
