# Generated by Django 4.2 on 2025-04-09 15:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0003_alter_student_user'),
        ('practices', '0003_alter_practice_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='practice',
            name='program',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='programs.program', verbose_name='Programa'),
            preserve_default=False,
        ),
    ]
