# Generated by Django 4.2 on 2025-04-09 17:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agreements', '0011_alter_agreementdocumentcomment_options'),
        ('practices', '0004_practice_program'),
    ]

    operations = [
        migrations.AddField(
            model_name='practice',
            name='agreement',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='agreements.agreement'),
        ),
    ]
