# Generated by Django 4.2 on 2025-04-10 16:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('practices', '0005_practice_agreement'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='documentpractice',
            options={'ordering': ['created_at'], 'verbose_name_plural': 'Documentos de práctica'},
        ),
        migrations.AlterModelOptions(
            name='internshiptracking',
            options={'ordering': ['created_at'], 'verbose_name_plural': 'Seguimiento de práctica'},
        ),
        migrations.AddField(
            model_name='documentpractice',
            name='uploaded_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Subido por'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='internshiptracking',
            name='created_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='creado por'),
            preserve_default=False,
        ),
    ]
