# Generated by Django 4.2 on 2025-04-24 03:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practices', '0006_alter_documentpractice_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='practicaloffer',
            options={'verbose_name': 'Oferta práctica', 'verbose_name_plural': 'Ofertas practicas'},
        ),
        migrations.AddField(
            model_name='practicaloffer',
            name='close_date',
            field=models.DateField(default=datetime.datetime(2025, 4, 24, 3, 37, 14, 669943, tzinfo=datetime.timezone.utc), verbose_name='Fecha de cierre'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='practicaloffer',
            name='responsibilities',
            field=models.TextField(default='a', verbose_name='Responsabilidades'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='practicaloffer',
            name='skills',
            field=models.TextField(default='a', verbose_name='Habilidades'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='practicaloffer',
            name='vacancies',
            field=models.PositiveIntegerField(default=1, verbose_name='Vacantes'),
        ),
    ]
