# Generated by Django 4.2 on 2025-05-17 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practices', '0007_alter_practicaloffer_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='practicaloffer',
            name='location',
            field=models.CharField(default='POpayán', max_length=100, verbose_name='Ubicación'),
            preserve_default=False,
        ),
    ]
