DEFENSE_STATUS_CHOICES = (
    ('PENDIENTE', 'PENDIENTE'),
    ('PROGRAMADA', 'PROGRAMADA'),
    ('COMPLETADA', 'COMPLETADA'),
    ('REPROGRAMADA', 'REPROGRAMADA'),
)

DEFENSE_RESULT_CHOICES = (
    ('APROBADO', 'APROBADO'),
    ('NO APROBADO', 'NO APROBADO'),
)

DEFENSE_TEACHER_ROLE_CHOICES = (
    ('JURADO', 'JURADO'),
    ('ASESOR', 'ASESOR'),
)