AGREEMENT_CHOICES = (
    ('ACTIVO', 'ACTIVO'),
    ('INACTIVO', 'INACTIVO'),
    ('VENCIDO', 'VENCIDO'),
    ('EN RENOVACIÓN', 'EN RENOVACIÓN'),
)

AGREEMENT_DOCUMENT_CHOICES = (
    ('PENDIENTE', 'PENDIENTE'),
    ('SUBIDO', 'SUBIDO'),
    ('APROBADO', 'APROBADO'),
    ('RECHAZADO', 'RECHAZADO')
)
AGREEMENT_DOCUMENT_UPDATE_STATUS_CHOICES = (
    ('APROBADO', 'APROBADO'),
    ('RECHAZADO', 'RECHAZADO')
)

AGREEMENT_DOCUMENTATION_STATUS = (
    ('PENDIENTE', 'PENDIENTE'),
    ('INCOMPLETA', 'INCOMPLETA'),
    ('COMPLETA', 'COMPLETA'),
)

AGREEMENT_STUDENT_STATUS = (
    ('ACTIVO', 'ACTIVO'),
    ('FINALIZADO', 'FINALIZADO'),
)