AGREEMENT_CHOICES = (
    ('ACTIVO', 'ACTIVO'),
    ('INACTIVO', 'INACTIVO'),
    ('VENCIDO', 'VENCIDO'),
    ('EN RENOVACIÓN', 'EN RENOVACIÓN'),
)

AGREEMENT_DOCUMENT_CHOICES = (
    ('PENDIENTE', 'PENDIENTE'),
    ('SUBIDO', 'SUBIDO'),
    ('APROBADO', 'APROBADO'),
    ('RECHAZADO', 'RECHAZADO')
)