# Generated by Django 4.2 on 2025-05-10 16:38

from django.db import migrations

ROLES_PERMISSIONS = {
    'ESTUDIANTE': [
        'view_company',
        'view_agreement',
        'add_documentpractice',
        'change_documentpractice',
        'view_documentpractice',
        'view_internshiptracking',
        'view_practicaloffer',
        'view_practice',
        'view_defense',
        'view_defensecomment'
    ],
    'DOCENTE': [
        'view_company',
        'view_student',
        'view_agreement',
        'add_documentpractice',
        'view_documentpractice',
        'add_internshiptracking',
        'change_internshiptracking',
        'view_internshiptracking',
        'view_practice',
        'view_defense',
        'add_defensecomment',
        'change_defensecomment',
        'delete_defensecomment',
        'view_defensecomment',
    ],
    'ADMINISTRADOR': 'all',
    'ORGANIZACIÓN': [
        'view_company',
        'view_agreement',
        'view_agreementstudentthrough',
        'add_agreementdocumentthrough',
        'change_agreementdocumentthrough',
        'view_agreementdocumentthrough',
        'view_practicalofferstudentthrough',
        'add_practicaloffer',
        'change_practicaloffer',
        'view_practicaloffer',
    ],
    'COORDINADORA ACADÉMICA': [
        'add_company',
        'change_company',
        'view_company',
        'view_program',
        'view_student',
        'add_agreement',
        'change_agreement',
        'view_agreement',
        'add_agreementstudentthrough',
        'change_agreementstudentthrough',
        'view_agreementstudentthrough',
        'add_documentagreement',
        'change_documentagreement',
        'view_documentagreement',
        'add_agreementdocumentthrough',
        'change_agreementdocumentthrough',
        'view_agreementdocumentthrough',
        'add_practicaloffer',
        'change_practicaloffer',
        'view_practicaloffer',
        'add_practice',
        'change_practice',
        'view_practice',
        'add_defense',
        'change_defense',
        'view_defense',
        'add_agreementdocumentcomment',
        'change_agreementdocumentcomment',
        'view_agreementdocumentcomment',
        'finish_defense'
    ]
}

def load_roles_permissions(apps, schema_editor):
    Group = apps.get_model('auth', 'Group')
    Permission = apps.get_model('auth', 'Permission')

    for role in ROLES_PERMISSIONS:
        group, _ = Group.objects.get_or_create(name = role)
        if ROLES_PERMISSIONS[role] == 'all':
            permissions = Permission.objects.all()
        else:
            permissions = Permission.objects.filter(codename__in = ROLES_PERMISSIONS[role])

        group.permissions.set(permissions)

def reverse_role_permissions(apps, schema_editor):
    Group = apps.get_model('auth', 'Group')
    for role in ROLES_PERMISSIONS:
        Group.objects.filter(name = role).delete()
    
class Migration(migrations.Migration):

    dependencies = [
        ('custom_auth', '0002_alter_customuser_email'),
    ]

    operations = [
        migrations.RunPython(load_roles_permissions, reverse_role_permissions)
    ]
