# Generated by Django 4.2 on 2025-03-15 23:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='fecha y hora de registro')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='última actualización')),
                ('name', models.CharField(help_text='Nombre.', max_length=255, verbose_name='Nombre')),
                ('phone', models.CharField(help_text='Número de teléfono.', max_length=20, verbose_name='Número de teléfono.')),
                ('email', models.EmailField(help_text='Dirección de correo electrónico.', max_length=255, verbose_name='Dirección de correo electrónico')),
                ('address', models.CharField(help_text='La dirección física.', max_length=500, verbose_name='La dirección física.')),
                ('nui', models.CharField(max_length=20, unique=True, verbose_name='Número único de identificación')),
            ],
            options={
                'verbose_name_plural': 'Organizaciones',
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='fecha y hora de registro')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='última actualización')),
                ('name', models.CharField(help_text='Nombre.', max_length=255, verbose_name='Nombre')),
                ('phone', models.CharField(help_text='Número de teléfono.', max_length=20, verbose_name='Número de teléfono.')),
                ('email', models.EmailField(help_text='Dirección de correo electrónico.', max_length=255, verbose_name='Dirección de correo electrónico')),
                ('address', models.CharField(help_text='La dirección física.', max_length=500, verbose_name='La dirección física.')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.company', verbose_name='Organización')),
            ],
            options={
                'verbose_name_plural': 'Contactos',
            },
        ),
    ]
