# Generated by Django 4.2 on 2025-03-16 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='email',
            field=models.EmailField(help_text='Dirección de correo electrónico.', max_length=255, unique=True, verbose_name='Dirección de correo electrónico'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.EmailField(help_text='Dirección de correo electrónico.', max_length=255, unique=True, verbose_name='Dirección de correo electrónico'),
        ),
    ]
