# Generated by Django 4.2 on 2025-03-17 23:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_alter_company_email_alter_contact_email'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'ordering': ['created_at'], 'verbose_name_plural': 'Organizaciones'},
        ),
        migrations.AlterModelOptions(
            name='contact',
            options={'ordering': ['created_at'], 'verbose_name_plural': 'Contactos'},
        ),
    ]
