# Generated by Django 4.2 on 2025-03-15 23:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('programs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agreement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='fecha y hora de registro')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='última actualización')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre')),
                ('initial_date', models.DateField(verbose_name='Fecha de inicio')),
                ('end_date', models.DateField(verbose_name='Fecha de finalización')),
                ('status', models.CharField(choices=[('ACTIVO', 'ACTIVO'), ('INACTIVO', 'INACTIVO'), ('VENCIDO', 'VENCIDO'), ('EN RENOVACIÓN', 'EN RENOVACIÓN')], max_length=100, verbose_name='Estado')),
                ('description', models.TextField(blank=True, max_length=1000, null=True, verbose_name='Descripción del convenio')),
                ('requirements', models.TextField(max_length=2000, verbose_name='Requisitos para aplicación')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='companies.company', verbose_name='Organización')),
            ],
            options={
                'verbose_name_plural': 'Convenios',
            },
        ),
        migrations.CreateModel(
            name='DocumentAgreement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='fecha y hora de registro')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='última actualización')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre del documento')),
                ('description', models.TextField(max_length=500, verbose_name='Descripción')),
                ('required', models.BooleanField(default=True, verbose_name='¿Obligatorio?')),
            ],
            options={
                'verbose_name_plural': 'Documentos convenio',
            },
        ),
        migrations.CreateModel(
            name='AgreementStudentThrough',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='fecha y hora de registro')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='última actualización')),
                ('agreement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agreements.agreement', verbose_name='Convenio')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='programs.student', verbose_name='Estudiante')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AgreementDocumentThrough',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='fecha y hora de registro')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='última actualización')),
                ('file', models.FileField(blank=True, null=True, upload_to='', verbose_name='Archivo')),
                ('status', models.CharField(default='PENDIENTE', max_length=100, verbose_name='Estado')),
                ('upload_date', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de subida')),
                ('agreement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agreements.agreement', verbose_name='Convenio')),
                ('document_agreement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agreements.documentagreement', verbose_name='Documento Convenio')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Subido por')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='agreement',
            name='documents',
            field=models.ManyToManyField(through='agreements.AgreementDocumentThrough', to='agreements.documentagreement', verbose_name='Documentos'),
        ),
        migrations.AddField(
            model_name='agreement',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='programs.program', verbose_name='Programa'),
        ),
        migrations.AddField(
            model_name='agreement',
            name='students',
            field=models.ManyToManyField(blank=True, through='agreements.AgreementStudentThrough', to='programs.student'),
        ),
    ]
