# Generated by Django 4.2 on 2025-03-16 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agreements', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agreement',
            name='status',
            field=models.CharField(choices=[('ACTIVO', 'ACTIVO'), ('INACTIVO', 'INACTIVO'), ('VENCIDO', 'VENCIDO'), ('EN RENOVACIÓN', 'EN RENOVACIÓN')], default='INACTIVO', max_length=100, verbose_name='Estado'),
        ),
    ]
