# Generated by Django 4.2 on 2025-03-17 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agreements', '0002_alter_agreement_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agreement',
            options={'ordering': ['created_at'], 'verbose_name_plural': 'Convenios'},
        ),
        migrations.AlterModelOptions(
            name='documentagreement',
            options={'ordering': ['created_at'], 'verbose_name_plural': 'Documentos convenio'},
        ),
        migrations.AddField(
            model_name='agreement',
            name='documentation_status',
            field=models.CharField(choices=[('PENDIENTE', 'PENDIENTE'), ('INCOMPLETA', 'INCOMPLETA'), ('COMPLETA', 'COMPLETA')], default='PENDIENTE', max_length=100, verbose_name='Estado de documentación'),
        ),
        migrations.AlterField(
            model_name='agreementdocumentthrough',
            name='status',
            field=models.CharField(choices=[('PENDIENTE', 'PENDIENTE'), ('SUBIDO', 'SUBIDO'), ('APROBADO', 'APROBADO'), ('RECHAZADO', 'RECHAZADO')], default='PENDIENTE', max_length=100, verbose_name='Estado'),
        ),
    ]
