# Generated by Django 4.2 on 2025-03-17 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agreements', '0003_alter_agreement_options_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='agreementdocumentthrough',
            constraint=models.UniqueConstraint(fields=('agreement', 'document_agreement'), name='unique_agreement_document'),
        ),
    ]
