# Generated by Django 4.2 on 2025-03-19 02:43

import agreements.models.agreement
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agreements', '0004_agreementdocumentthrough_unique_agreement_document'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documentagreement',
            name='required',
        ),
        migrations.AlterField(
            model_name='agreementdocumentthrough',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=agreements.models.agreement.custom_upload_document, verbose_name='Archivo'),
        ),
    ]
