# Generated by Django 4.2 on 2025-03-19 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agreements', '0005_remove_documentagreement_required_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agreementdocumentthrough',
            options={'ordering': ['created_at']},
        ),
        migrations.AddField(
            model_name='agreementstudentthrough',
            name='status',
            field=models.CharField(choices=[('ACTIVO', 'ACTIVO'), ('FINALIZADO', 'FINALIZADO')], default='ACTIVO', max_length=100, verbose_name='Estado'),
        ),
    ]
