# Generated by Django 4.2 on 2025-03-21 16:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('agreements', '0006_alter_agreementdocumentthrough_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgreementDocumentComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='fecha y hora de registro')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='última actualización')),
                ('previous_state', models.CharField(choices=[('PENDIENTE', 'PENDIENTE'), ('SUBIDO', 'SUBIDO'), ('APROBADO', 'APROBADO'), ('RECHAZADO', 'RECHAZADO')], max_length=100, null=True, verbose_name='Estado anterior')),
                ('new_state', models.CharField(choices=[('PENDIENTE', 'PENDIENTE'), ('SUBIDO', 'SUBIDO'), ('APROBADO', 'APROBADO'), ('RECHAZADO', 'RECHAZADO')], max_length=100, verbose_name='Nuevo estado')),
                ('comment', models.TextField(max_length=500, verbose_name='Comentario')),
                ('agreement_document', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='agreements.agreementdocumentthrough', verbose_name='Documento del convenio')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
            ],
            options={
                'verbose_name_plural': 'Comentarios de documento de convenio',
                'ordering': ['created_at'],
            },
        ),
    ]
