# Generated by Django 4.2 on 2025-03-25 02:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agreements', '0007_agreementdocumentcomment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agreementdocumentcomment',
            name='agreement_document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agreements.agreementdocumentthrough', verbose_name='Documento del convenio'),
        ),
    ]
