# Generated by Django 4.2 on 2025-03-25 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agreements', '0008_alter_agreementdocumentcomment_agreement_document'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agreement',
            name='requirements',
        ),
    ]
