# Generated by Django 4.2 on 2025-03-28 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agreements', '0009_remove_agreement_requirements'),
    ]

    operations = [
        migrations.AddField(
            model_name='agreement',
            name='agreement_type',
            field=models.CharField(choices=[('ESPECÍFICO', 'ESPECÍFICO'), ('MACRO', 'MACRO')], default='ESPECÍFICO', max_length=100, verbose_name='Tipo de convenio'),
        ),
        migrations.AddField(
            model_name='agreement',
            name='scope',
            field=models.CharField(choices=[('NACIONAL', 'NACIONAL'), ('INTERNACIONAL', 'INTERNACIONAL')], default='NACIONAL', max_length=100, verbose_name='Alcance'),
        ),
    ]
