# Generated by Django 4.2 on 2025-04-07 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agreements', '0010_agreement_agreement_type_agreement_scope'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agreementdocumentcomment',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'Comentarios de documento de convenio'},
        ),
    ]
