# Generated by Django 4.2 on 2025-05-17 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agreements', '0011_alter_agreementdocumentcomment_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agreement',
            options={'ordering': ['created_at'], 'permissions': [('toggle_status', 'Puede cambiar el estado del convenio')], 'verbose_name_plural': 'Convenios'},
        ),
    ]
