# Generated by Django 4.2 on 2025-05-17 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agreements', '0012_alter_agreement_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='documentagreement',
            options={'ordering': ['created_at'], 'permissions': [('toggle_status', 'Puede cambiar el estado del documento')], 'verbose_name_plural': 'Documentos convenio'},
        ),
        migrations.AddField(
            model_name='documentagreement',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
