# Generated by Django 4.2 on 2025-05-17 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agreements', '0013_alter_documentagreement_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='documentagreement',
            options={'ordering': ['created_at'], 'permissions': [('toggle_status_document', 'Puede cambiar el estado del documento')], 'verbose_name_plural': 'Documentos convenio'},
        ),
    ]
