# Generated by Django 4.2 on 2025-11-16 23:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('agreements', '0014_alter_documentagreement_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Favoritos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='fecha y hora de registro')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='última actualización')),
                ('agreement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agreements.agreement', verbose_name='Convenio')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name_plural': 'Convenios Favoritos',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='favoritos',
            constraint=models.UniqueConstraint(fields=('user', 'agreement'), name='unique_user_agreement_favorite'),
        ),
    ]
