# Generated by Django 4.2 on 2025-03-15 23:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='fecha y hora de registro')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='última actualización')),
                ('name', models.CharField(max_length=250, unique=True, verbose_name='Nombre')),
                ('code', models.PositiveIntegerField(unique=True, verbose_name='Código')),
            ],
            options={
                'verbose_name_plural': 'Programas',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='fecha y hora de registro')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='última actualización')),
                ('first_name', models.CharField(max_length=100, verbose_name='Primer nombre')),
                ('second_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Segundo nombre')),
                ('first_surname', models.CharField(max_length=100, verbose_name='Primer apeliido')),
                ('second_surname', models.CharField(blank=True, max_length=100, null=True, verbose_name='Segundo apellido')),
                ('code', models.PositiveIntegerField(db_index=True, unique=True, verbose_name='Código')),
                ('document_number', models.CharField(db_index=True, max_length=11, unique=True, verbose_name='Número de documento')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Correo electrónico')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='programs.program', verbose_name='Programa')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name_plural': 'Estudiantes',
            },
        ),
    ]
