# Generated by Django 4.2 on 2025-03-19 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='program',
            options={'ordering': ['created_at'], 'verbose_name_plural': 'Programas'},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['created_at'], 'verbose_name_plural': 'Estudiantes'},
        ),
    ]
