# Generated by Django 4.2 on 2025-04-17 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0003_alter_student_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='full_name',
            field=models.CharField(db_index=True, default='Default', editable=False, max_length=300, verbose_name='Nombre completo'),
            preserve_default=False,
        ),
    ]
