# Generated by Django 4.2 on 2025-04-17 02:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0004_student_full_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['created_at'], 'verbose_name': 'Estudiante', 'verbose_name_plural': 'Estudiantes'},
        ),
    ]
